/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "auto_microservices_constants.h"

namespace auto_microservices {

const auto_microservicesConstants g_auto_microservices_constants;

auto_microservicesConstants::auto_microservicesConstants() {
}

} // namespace

