/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef auto_microservices_CONSTANTS_H
#define auto_microservices_CONSTANTS_H

#include "auto_microservices_types.h"

namespace auto_microservices {

class auto_microservicesConstants {
 public:
  auto_microservicesConstants();

};

extern const auto_microservicesConstants g_auto_microservices_constants;

} // namespace

#endif
