/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef service_11_H
#define service_11_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "auto_microservices_types.h"

namespace auto_microservices {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class service_11If {
 public:
  virtual ~service_11If() {}
  virtual void rpc_11(const std::map<std::string, std::string> & carrier) = 0;
};

class service_11IfFactory {
 public:
  typedef service_11If Handler;

  virtual ~service_11IfFactory() {}

  virtual service_11If* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(service_11If* /* handler */) = 0;
};

class service_11IfSingletonFactory : virtual public service_11IfFactory {
 public:
  service_11IfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<service_11If>& iface) : iface_(iface) {}
  virtual ~service_11IfSingletonFactory() {}

  virtual service_11If* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(service_11If* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<service_11If> iface_;
};

class service_11Null : virtual public service_11If {
 public:
  virtual ~service_11Null() {}
  void rpc_11(const std::map<std::string, std::string> & /* carrier */) {
    return;
  }
};

typedef struct _service_11_rpc_11_args__isset {
  _service_11_rpc_11_args__isset() : carrier(false) {}
  bool carrier :1;
} _service_11_rpc_11_args__isset;

class service_11_rpc_11_args {
 public:

  service_11_rpc_11_args(const service_11_rpc_11_args&);
  service_11_rpc_11_args& operator=(const service_11_rpc_11_args&);
  service_11_rpc_11_args() {
  }

  virtual ~service_11_rpc_11_args() throw();
  std::map<std::string, std::string>  carrier;

  _service_11_rpc_11_args__isset __isset;

  void __set_carrier(const std::map<std::string, std::string> & val);

  bool operator == (const service_11_rpc_11_args & rhs) const
  {
    if (!(carrier == rhs.carrier))
      return false;
    return true;
  }
  bool operator != (const service_11_rpc_11_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const service_11_rpc_11_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class service_11_rpc_11_pargs {
 public:


  virtual ~service_11_rpc_11_pargs() throw();
  const std::map<std::string, std::string> * carrier;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _service_11_rpc_11_result__isset {
  _service_11_rpc_11_result__isset() : se(false) {}
  bool se :1;
} _service_11_rpc_11_result__isset;

class service_11_rpc_11_result {
 public:

  service_11_rpc_11_result(const service_11_rpc_11_result&);
  service_11_rpc_11_result& operator=(const service_11_rpc_11_result&);
  service_11_rpc_11_result() {
  }

  virtual ~service_11_rpc_11_result() throw();
  ServiceException se;

  _service_11_rpc_11_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const service_11_rpc_11_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const service_11_rpc_11_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const service_11_rpc_11_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _service_11_rpc_11_presult__isset {
  _service_11_rpc_11_presult__isset() : se(false) {}
  bool se :1;
} _service_11_rpc_11_presult__isset;

class service_11_rpc_11_presult {
 public:


  virtual ~service_11_rpc_11_presult() throw();
  ServiceException se;

  _service_11_rpc_11_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class service_11Client : virtual public service_11If {
 public:
  service_11Client(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  service_11Client(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void rpc_11(const std::map<std::string, std::string> & carrier);
  void send_rpc_11(const std::map<std::string, std::string> & carrier);
  void recv_rpc_11();
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class service_11Processor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<service_11If> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (service_11Processor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_rpc_11(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  service_11Processor(::apache::thrift::stdcxx::shared_ptr<service_11If> iface) :
    iface_(iface) {
    processMap_["rpc_11"] = &service_11Processor::process_rpc_11;
  }

  virtual ~service_11Processor() {}
};

class service_11ProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  service_11ProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< service_11IfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< service_11IfFactory > handlerFactory_;
};

class service_11Multiface : virtual public service_11If {
 public:
  service_11Multiface(std::vector<apache::thrift::stdcxx::shared_ptr<service_11If> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~service_11Multiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<service_11If> > ifaces_;
  service_11Multiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<service_11If> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void rpc_11(const std::map<std::string, std::string> & carrier) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->rpc_11(carrier);
    }
    ifaces_[i]->rpc_11(carrier);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class service_11ConcurrentClient : virtual public service_11If {
 public:
  service_11ConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  service_11ConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void rpc_11(const std::map<std::string, std::string> & carrier);
  int32_t send_rpc_11(const std::map<std::string, std::string> & carrier);
  void recv_rpc_11(const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
