/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef service_10_H
#define service_10_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "auto_microservices_types.h"

namespace auto_microservices {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class service_10If {
 public:
  virtual ~service_10If() {}
  virtual void rpc_10(const std::map<std::string, std::string> & carrier) = 0;
};

class service_10IfFactory {
 public:
  typedef service_10If Handler;

  virtual ~service_10IfFactory() {}

  virtual service_10If* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(service_10If* /* handler */) = 0;
};

class service_10IfSingletonFactory : virtual public service_10IfFactory {
 public:
  service_10IfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<service_10If>& iface) : iface_(iface) {}
  virtual ~service_10IfSingletonFactory() {}

  virtual service_10If* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(service_10If* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<service_10If> iface_;
};

class service_10Null : virtual public service_10If {
 public:
  virtual ~service_10Null() {}
  void rpc_10(const std::map<std::string, std::string> & /* carrier */) {
    return;
  }
};

typedef struct _service_10_rpc_10_args__isset {
  _service_10_rpc_10_args__isset() : carrier(false) {}
  bool carrier :1;
} _service_10_rpc_10_args__isset;

class service_10_rpc_10_args {
 public:

  service_10_rpc_10_args(const service_10_rpc_10_args&);
  service_10_rpc_10_args& operator=(const service_10_rpc_10_args&);
  service_10_rpc_10_args() {
  }

  virtual ~service_10_rpc_10_args() throw();
  std::map<std::string, std::string>  carrier;

  _service_10_rpc_10_args__isset __isset;

  void __set_carrier(const std::map<std::string, std::string> & val);

  bool operator == (const service_10_rpc_10_args & rhs) const
  {
    if (!(carrier == rhs.carrier))
      return false;
    return true;
  }
  bool operator != (const service_10_rpc_10_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const service_10_rpc_10_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class service_10_rpc_10_pargs {
 public:


  virtual ~service_10_rpc_10_pargs() throw();
  const std::map<std::string, std::string> * carrier;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _service_10_rpc_10_result__isset {
  _service_10_rpc_10_result__isset() : se(false) {}
  bool se :1;
} _service_10_rpc_10_result__isset;

class service_10_rpc_10_result {
 public:

  service_10_rpc_10_result(const service_10_rpc_10_result&);
  service_10_rpc_10_result& operator=(const service_10_rpc_10_result&);
  service_10_rpc_10_result() {
  }

  virtual ~service_10_rpc_10_result() throw();
  ServiceException se;

  _service_10_rpc_10_result__isset __isset;

  void __set_se(const ServiceException& val);

  bool operator == (const service_10_rpc_10_result & rhs) const
  {
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const service_10_rpc_10_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const service_10_rpc_10_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _service_10_rpc_10_presult__isset {
  _service_10_rpc_10_presult__isset() : se(false) {}
  bool se :1;
} _service_10_rpc_10_presult__isset;

class service_10_rpc_10_presult {
 public:


  virtual ~service_10_rpc_10_presult() throw();
  ServiceException se;

  _service_10_rpc_10_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class service_10Client : virtual public service_10If {
 public:
  service_10Client(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  service_10Client(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void rpc_10(const std::map<std::string, std::string> & carrier);
  void send_rpc_10(const std::map<std::string, std::string> & carrier);
  void recv_rpc_10();
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class service_10Processor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<service_10If> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (service_10Processor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_rpc_10(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  service_10Processor(::apache::thrift::stdcxx::shared_ptr<service_10If> iface) :
    iface_(iface) {
    processMap_["rpc_10"] = &service_10Processor::process_rpc_10;
  }

  virtual ~service_10Processor() {}
};

class service_10ProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  service_10ProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< service_10IfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< service_10IfFactory > handlerFactory_;
};

class service_10Multiface : virtual public service_10If {
 public:
  service_10Multiface(std::vector<apache::thrift::stdcxx::shared_ptr<service_10If> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~service_10Multiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<service_10If> > ifaces_;
  service_10Multiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<service_10If> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void rpc_10(const std::map<std::string, std::string> & carrier) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->rpc_10(carrier);
    }
    ifaces_[i]->rpc_10(carrier);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class service_10ConcurrentClient : virtual public service_10If {
 public:
  service_10ConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  service_10ConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void rpc_10(const std::map<std::string, std::string> & carrier);
  int32_t send_rpc_10(const std::map<std::string, std::string> & carrier);
  void recv_rpc_10(const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
